FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG NEXT_PUBLIC_SOLANA_MAINNET_RPC
ENV NEXT_PUBLIC_SOLANA_MAINNET_RPC=$NEXT_PUBLIC_SOLANA_MAINNET_RPC
ARG NEXT_PUBLIC_SOLANA_DEVNET_RPC
ENV NEXT_PUBLIC_SOLANA_DEVNET_RPC=$NEXT_PUBLIC_SOLANA_DEVNET_RPC
ARG NEXT_PUBLIC_KIVO_NETWORK
ENV NEXT_PUBLIC_KIVO_NETWORK=$NEXT_PUBLIC_KIVO_NETWORK
ARG NEXT_PUBLIC_KIVO_PROGRAM_ID
ENV NEXT_PUBLIC_KIVO_PROGRAM_ID=$NEXT_PUBLIC_KIVO_PROGRAM_ID
ARG NEXT_PUBLIC_KIVO_TREASURY
ENV NEXT_PUBLIC_KIVO_TREASURY=$NEXT_PUBLIC_KIVO_TREASURY
RUN npm run build

FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production PORT=3000
COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["npm", "run", "start"]
