services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_SOLANA_MAINNET_RPC: ${NEXT_PUBLIC_SOLANA_MAINNET_RPC:-https://api.mainnet-beta.solana.com}
        NEXT_PUBLIC_SOLANA_DEVNET_RPC: ${NEXT_PUBLIC_SOLANA_DEVNET_RPC:-https://api.devnet.solana.com}
        NEXT_PUBLIC_KIVO_NETWORK: ${NEXT_PUBLIC_KIVO_NETWORK:-devnet}
        NEXT_PUBLIC_KIVO_PROGRAM_ID: ${NEXT_PUBLIC_KIVO_PROGRAM_ID:-7rJ2978K9SpqB4d7FAGrquhC7Gy2iJehxB4EohDZEB8}
        NEXT_PUBLIC_KIVO_TREASURY: ${NEXT_PUBLIC_KIVO_TREASURY:-84HCJtzmvWF2tB4SCr8hmDymLN4Rz6u8jJoyaqwLjSRR}
    ports:
      - "3000:3000"
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_SESSION_SECRET: ${ADMIN_SESSION_SECRET}
      UPSTASH_REDIS_REST_URL: ${UPSTASH_REDIS_REST_URL}
      UPSTASH_REDIS_REST_TOKEN: ${UPSTASH_REDIS_REST_TOKEN}
      SOLANA_MAINNET_RPC: ${SOLANA_MAINNET_RPC:-https://api.mainnet-beta.solana.com}
      SOLANA_MARKET_RPC: ${SOLANA_MARKET_RPC:-https://api.devnet.solana.com}
      NEXT_PUBLIC_KIVO_NETWORK: ${NEXT_PUBLIC_KIVO_NETWORK:-devnet}
      NEXT_PUBLIC_KIVO_PROGRAM_ID: ${NEXT_PUBLIC_KIVO_PROGRAM_ID:-7rJ2978K9SpqB4d7FAGrquhC7Gy2iJehxB4EohDZEB8}
      NEXT_PUBLIC_KIVO_TREASURY: ${NEXT_PUBLIC_KIVO_TREASURY:-84HCJtzmvWF2tB4SCr8hmDymLN4Rz6u8jJoyaqwLjSRR}
      NEXT_PUBLIC_SOLANA_MAINNET_RPC: ${NEXT_PUBLIC_SOLANA_MAINNET_RPC:-https://api.mainnet-beta.solana.com}
      NEXT_PUBLIC_SOLANA_DEVNET_RPC: ${NEXT_PUBLIC_SOLANA_DEVNET_RPC:-https://api.devnet.solana.com}
    restart: unless-stopped
