services:
  - type: web
    name: kivo-devnet
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_SOLANA_MAINNET_RPC
        value: https://api.mainnet-beta.solana.com
      - key: NEXT_PUBLIC_SOLANA_DEVNET_RPC
        value: https://api.devnet.solana.com
      - key: SOLANA_MAINNET_RPC
        value: https://api.mainnet-beta.solana.com
      - key: SOLANA_MARKET_RPC
        value: https://api.devnet.solana.com
      - key: NEXT_PUBLIC_KIVO_NETWORK
        value: devnet
      - key: NEXT_PUBLIC_KIVO_PROGRAM_ID
        value: 7rJ2978K9SpqB4d7FAGrquhC7Gy2iJehxB4EohDZEB8
      - key: NEXT_PUBLIC_KIVO_TREASURY
        value: 84HCJtzmvWF2tB4SCr8hmDymLN4Rz6u8jJoyaqwLjSRR
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SESSION_SECRET
        generateValue: true
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
