[package]
name = "kivo-market"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "kivo_market"

[features]
default = []
no-entrypoint = []
cpi = ["no-entrypoint"]
no-idl = []
anchor-debug = []
custom-heap = []
custom-panic = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.32.1", features = ["token_2022", "associated_token"] }
kivo-market-math = { path = "../kivo-market-math" }
spl-token-2022 = "8.0.1"
